# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Data Out Loud
email: robinphetsa@icloud.com
author: Robin Phetsavong
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016 Robin Phetsavong. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
 # - title: wordpress
  #  url: https://robinphetsavongdata.wordpress.com
  #  text: Wordpress
  - title: github
    url: https://github.com/robinphetsa
    text: Github
  - title: linkedin
    url: https://www.linkedin.com/in/robin-phetsavong-931003a1
    text: LinkedIn

contact:
  - title: mobile
    #url: javascript:void(0);#
    url: tel:5592594705
    text: 559-259-4706
  - title: envelope
    url: mailto:robinphetsa@icloud.com;
    text: robinphetsa@icloud.com
#  - title: location-arrow#
#    text: Location:#
    

