# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Data Out Loud
email: robinphetsa@icloud.com
author: Robin Phetsavong
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016 Robin Phetsavong. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
#  - title: twitter
 #   url: https://twitter.com/robinphetsavong#
  - title: github
    url: https://github.com/robinphetsa
    text: Github
  - title: linkedin
    url: https://www.linkedin.com/in/robin-phetsavong-931003a1
    text: LinkedIn
  - title: mobile
    url: #
    text: 559-259-4706
